_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.7
            "8":
                - 2
                - 5
                - 9
            "12": 0.19.7
            "13": linux-x86_64
